import datetime


def generate_report(state: dict) -> str:
    """
    Agent 4 - Reporter.
    Creates a structured Markdown report from the pipeline state data.
    """
    difficulty_dist = state.get("difficulty", {"Easy": "0%", "Medium": "0%", "Hard": "0%"})
    problems = state.get("problems", ["No problems identified."])
    principles = state.get("principles", ["No principles retrieved."])
    recommendations = state.get("recommendations", ["No recommendations available."])

    date_str = datetime.datetime.now().strftime("%B %d, %Y")

    # Section 1 & 2
    report_md = f"""# Assessment Quality Report
*Generated on {date_str}*

## 1. Assessment Quality Summary
Based on the provided metrics and AI analysis, the assessment has been evaluated across multiple dimensions including difficulty balancing, topic coverage, and cognitive load. The findings highlight areas of improvement to ensure a fairer and more effective evaluation of student competencies.

## 2. Question Difficulty Distribution
- **Easy:** {difficulty_dist.get("Easy", "N/A")}
- **Medium:** {difficulty_dist.get("Medium", "N/A")}
- **Hard:** {difficulty_dist.get("Hard", "N/A")}

## 3. Identified Learning Gaps & Exam Issues
"""

    # Section 3
    for p in problems:
        report_md += f"- {p}\n"

    # Section 4
    report_md += "\n## 4. Recommended Assessment Improvements\n"
    for r in recommendations:
        report_md += f"- {r}\n"

    # Section 5
    report_md += "\n## 5. Supporting Pedagogical References\n"
    for pr in principles:
        report_md += f"- {pr}\n"

    # Section 6
    report_md += """
## 6. Educational and Ethical Disclaimers
*Disclaimer: This report is generated by an AI assistant intended to serve as a supportive tool for educators. It does not replace professional pedagogical judgment. Ensure that the incorporated recommendations align with your institution's specific curriculum standards and ethical guidelines.*
"""
    return report_md
