"""
Agent 4: Reporter Agent.
Responsible for formatting the pipeline state into a structured Markdown 
report suitable for both UI display and PDF export.
"""
import datetime


def generate_report(state: dict) -> str:
    """
    Agent 4 - Reporter.
    Creates a detailed Markdown report from the pipeline state data, 
    including metrics on difficulty distribution, topic performance, 
    and pedagogical improvement recommendations.
    """
    difficulty_dist = state.get("difficulty", {"Easy": "0%", "Medium": "0%", "Hard": "0%"})
    problems = state.get("problems", ["No problems identified."])
    principles = state.get("principles", ["No principles retrieved."])
    recommendations = state.get("recommendations", ["No recommendations available."])
    topic_analysis = state.get("topic_analysis", {})

    total = difficulty_dist.get("total", 1)
    def get_pct(key):
        count = difficulty_dist.get(key, 0)
        return f"{count} ({count/total*100:.1f}%)" if total > 0 else f"{count} (0%)"

    metadata = state.get("metadata", {})
    avg_score = metadata.get("avg_student_score", "N/A")
    total_resp = metadata.get("total_responses", 0)

    date_str = datetime.datetime.now().strftime("%B %d, %Y")

    # Section 1 & 2
    report_md = f"""# Assessment Quality Report
*Generated on {date_str}*

## 1. Executive Performance Summary
- **Total Questions Analyzed:** {metadata.get('total_questions', total)}
- **Average Student Score:** {avg_score} (from {total_resp} responses)
- **Primary Concern:** {"Difficulty imbalance" if "difficulty" in (problems[0].lower() if problems else "") else "Content coverage"}

## 2. Assessment Qualitative Analysis
Based on the provided metrics and AI analysis, the assessment has been evaluated across multiple dimensions including difficulty balancing, topic coverage, and cognitive load. The findings highlight areas of improvement to ensure a fairer and more effective evaluation of student competencies.

## 3. Question Difficulty Distribution
- **Easy:** {get_pct("Easy")}
- **Medium:** {get_pct("Medium")}
- **Hard:** {get_pct("Hard")}
- **Total Questions:** {total}

"""
    # Addition: Topic Analysis
    if topic_analysis:
        report_md += "## 4. Topic-Level Performance Data\n"
        for topic, data in topic_analysis.items():
            report_md += f"- **{topic}**: Score {data.get('score', 0)} ({data.get('difficulty', 'Unknown')})\n"
        report_md += "\n"
        section_num = 5
    else:
        section_num = 4

    report_md += f"## {section_num}. Identified Learning Gaps & Exam Issues\n"

    # Section 3
    for p in problems:
        report_md += f"- {p}\n"

    section_num += 1
    report_md += f"\n## {section_num}. Recommended Assessment Improvements\n"
    for r in recommendations:
        report_md += f"- {r}\n"

    section_num += 1
    report_md += f"\n## {section_num}. Supporting Pedagogical References\n"
    for pr in principles:
        report_md += f"- {pr}\n"

    section_num += 1
    report_md += f"""
## {section_num}. Educational and Ethical Disclaimers
*Disclaimer: This report is generated by an AI assistant intended to serve as a **supportive tool for educators**. It does not replace professional pedagogical judgment. Ensure that the incorporated recommendations align with your institution's specific curriculum standards and ethical guidelines.*
"""
    return report_md
